// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSdwdoW6Qcn2NV1Ir5iB6TAWc0NFC-IDQ',
    appId: '1:686693247591:web:b37d145c5de10bbef4c2c2',
    messagingSenderId: '686693247591',
    projectId: 'sync-local-7f559',
    authDomain: 'sync-local-7f559.firebaseapp.com',
    storageBucket: 'sync-local-7f559.firebasestorage.app',
    measurementId: 'G-VNQ79MN1QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3WwfGa4VdxJVHUm25n9LWwq6wq71g8w',
    appId: '1:686693247591:android:e95a5cb29cb38e11f4c2c2',
    messagingSenderId: '686693247591',
    projectId: 'sync-local-7f559',
    storageBucket: 'sync-local-7f559.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSdwdoW6Qcn2NV1Ir5iB6TAWc0NFC-IDQ',
    appId: '1:686693247591:web:6e50ed1751226d69f4c2c2',
    messagingSenderId: '686693247591',
    projectId: 'sync-local-7f559',
    authDomain: 'sync-local-7f559.firebaseapp.com',
    storageBucket: 'sync-local-7f559.firebasestorage.app',
    measurementId: 'G-VNMRF752VT',
  );
}
