// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrmW4XhvlQiT4Bou_Hb794EC_YfJpeUM',
    appId: '1:582566355394:web:eca453f7e349a26fb7765b',
    messagingSenderId: '582566355394',
    projectId: 'fribe-db',
    authDomain: 'fribe-db.firebaseapp.com',
    storageBucket: 'fribe-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9O1-y-etfnDxcEe5u-thnyQaCmyeUUI',
    appId: '1:582566355394:android:be56864055be8112b7765b',
    messagingSenderId: '582566355394',
    projectId: 'fribe-db',
    storageBucket: 'fribe-db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrmW4XhvlQiT4Bou_Hb794EC_YfJpeUM',
    appId: '1:582566355394:web:6a9900333a461e2fb7765b',
    messagingSenderId: '582566355394',
    projectId: 'fribe-db',
    authDomain: 'fribe-db.firebaseapp.com',
    storageBucket: 'fribe-db.firebasestorage.app',
  );
}
