// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZiJwx0SseDr3EwNLGIXVA_Nytlom0fs8',
    appId: '1:127079901950:android:7e47799ec01967cd2153af',
    messagingSenderId: '127079901950',
    projectId: 'chat-v2-3115d',
    databaseURL: 'https://chat-v2-3115d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-v2-3115d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO0c96TBox6UbLBWIzHiHDShLKga2Giik',
    appId: '1:127079901950:web:2af61561d311c2032153af',
    messagingSenderId: '127079901950',
    projectId: 'chat-v2-3115d',
    authDomain: 'chat-v2-3115d.firebaseapp.com',
    databaseURL: 'https://chat-v2-3115d-default-rtdb.firebaseio.com',
    storageBucket: 'chat-v2-3115d.firebasestorage.app',
    measurementId: 'G-5RQ64YHLNS',
  );
}
