// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIbCj8tuR4Iv9o8K-HwyU_4IDIcOwwGtA',
    appId: '1:948361375925:android:f0aa391bbbc23049048efc',
    messagingSenderId: '948361375925',
    projectId: 'shop-app-d5e68',
    databaseURL: 'https://shop-app-d5e68-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-d5e68.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhyddVyixF18KNvBxrIHvjgxrRtSmVRHE',
    appId: '1:948361375925:web:c538ba25c497ea3f048efc',
    messagingSenderId: '948361375925',
    projectId: 'shop-app-d5e68',
    authDomain: 'shop-app-d5e68.firebaseapp.com',
    databaseURL: 'https://shop-app-d5e68-default-rtdb.firebaseio.com',
    storageBucket: 'shop-app-d5e68.firebasestorage.app',
  );

}